---
- name: Ensure that curl package is installed (Debian)
  apt:
    name: curl
    state: installed
    update_cache: yes
    cache_valid_time: 600
  when: ansible_os_family == "Debian"

- name: Ensure that curl package is installed (RedHat)
  yum:
    name: curl
    state: installed
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Create Slack notification script
  template:
    src: send_slack_on_ssh_login.sh.j2
    dest: /usr/local/bin/send_slack_on_ssh_login.sh
    mode: 0744

- name: Enable Slack notification script in SSHd PAM config file
  lineinfile:
    dest: /etc/pam.d/sshd
    line: "session optional pam_exec.so /usr/local/bin/send_slack_on_ssh_login.sh"
